### ISSUE TITLE
[Automated Report] com.intellij.diagnostic.PluginException: Cannot init component state (componentName=CsvFileAttributes, componentClass=CsvFileAttributes) [Plugin: net.seesharpsoft.intellij.plugins.csv]

### ISSUE THREAD

**Issue by alexoooo** [SeeSharpSoft/intellij-csv-validator#376] opened 2022-11-23 18:02 UTC
Message
---
<no message>

Stacktrace
---
com.intellij.diagnostic.PluginException: Cannot init component state (componentName=CsvFileAttributes, componentClass=CsvFileAttributes) [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:148)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:535)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at net.seesharpsoft.intellij.plugins.csv.components.CsvFileAttributes.getInstance(CsvFileAttributes.java:43)
	at net.seesharpsoft.intellij.plugins.csv.CsvPlugin$1.run(CsvPlugin.java:55)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: C:\Users\ao\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\Kotlin\kotlinc doesn't exist
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayoutWhenRunInProduction.resolve(KotlinPluginLayout.kt:93)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayoutWhenRunInProduction.access$resolve(KotlinPluginLayout.kt:82)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayoutWhenRunInProduction$kotlinc$2.invoke(KotlinPluginLayout.kt:87)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayoutWhenRunInProduction$kotlinc$2.invoke(KotlinPluginLayout.kt:82)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayoutWhenRunInProduction.getKotlinc(KotlinPluginLayout.kt)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayout$standaloneCompilerVersion$2.invoke(KotlinPluginLayout.kt:42)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayout$standaloneCompilerVersion$2.invoke(KotlinPluginLayout.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayout.getStandaloneCompilerVersion(KotlinPluginLayout.kt)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayout$Companion$instance$2.invoke(KotlinPluginLayout.kt:72)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayout$Companion$instance$2.invoke(KotlinPluginLayout.kt:52)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinPluginLayout$Companion.getInstance(KotlinPluginLayout.kt)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinArtifactsDownloader.getUnpackedKotlinDistPath(KotlinArtifactsDownloader.kt:31)
	at org.jetbrains.kotlin.idea.macros.KotlinBundledPathMacroContributor.getProjectPathMacros(KotlinBundledPathMacroContributor.kt:41)
	at com.intellij.openapi.components.impl.ProjectWidePathMacroContributor.getAllMacros(ProjectWidePathMacroContributor.java:38)
	at com.intellij.openapi.components.impl.ProjectPathMacroManager.getExpandMacroMap(ProjectPathMacroManager.java:49)
	at com.intellij.openapi.components.PathMacroManager.expandPaths(PathMacroManager.java:134)
	at com.intellij.configurationStore.TrackingPathMacroSubstitutorImpl.expandPaths(TrackingPathMacroSubstitutorImpl.kt)
	at com.intellij.openapi.components.impl.stores.FileStorageCoreUtil.load(FileStorageCoreUtil.java:36)
	at com.intellij.configurationStore.XmlElementStorage.loadState(XmlElementStorage.kt:85)
	at com.intellij.configurationStore.XmlElementStorage.loadData(XmlElementStorage.kt:49)
	at com.intellij.configurationStore.XmlElementStorage.loadData(XmlElementStorage.kt:32)
	at com.intellij.configurationStore.StateStorageBase.getStorageData(StateStorageBase.kt:52)
	at com.intellij.configurationStore.StorageBaseEx.createGetSession$intellij_platform_configurationStore_impl(StorageBaseEx.kt:15)
	at com.intellij.configurationStore.StorageBaseExKt.createStateGetter(StorageBaseEx.kt:26)
	at com.intellij.configurationStore.ComponentStoreImpl.doCreateStateGetter(ComponentStoreImpl.kt:489)
	at com.intellij.configurationScript.providers.MyProjectStore.doCreateStateGetter(ConfigurationScriptProjectStoreFactory.kt:46)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:421)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	... 38 more

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.0.1-222, package=null, isBundled=false), packagePrefix=null, instanceId=91, state=active)

IDE
---
IntelliJ IDEA (IC-222.4345.14)

**Comment by SeeSharpSoft** [comment] 2023-02-09 10:01
duplicate of #410

**Closed by SeeSharpSoft** 2023-02-09 10:01 UTC
