### ISSUE TITLE
[Automated Report] com.intellij.diagnostic.PluginException: 548 ms to call on EDT CsvChangeEscapeCharacterActionGroup#update@EditorPopup (net.seesharpsoft.intellij.plugins.csv.actions.CsvChangeEscapeCharacterActionGroup). Revise AnAction.getActionUpdateThread property [Plugin: net.seesharpsoft.intellij.plugins.csv]

### ISSUE THREAD

**Issue by Rsubham01** [SeeSharpSoft/intellij-csv-validator#446] opened 2023-04-03 22:34 UTC
Message
---
<no message>

Stacktrace
---
com.intellij.diagnostic.PluginException: 548 ms to call on EDT CsvChangeEscapeCharacterActionGroup#update@EditorPopup (net.seesharpsoft.intellij.plugins.csv.actions.CsvChangeEscapeCharacterActionGroup). Revise AnAction.getActionUpdateThread property [Plugin: net.seesharpsoft.intellij.plugins.csv]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:140)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:127)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:702)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:548)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:521)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1538)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:521)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:372)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:392)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:424)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:420)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:391)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Throwable: EDT-trace-at-102-ms (1/5)
		at net.seesharpsoft.intellij.plugins.csv.CsvHelper.isCsvFile(CsvHelper.java:89)
		at net.seesharpsoft.intellij.plugins.csv.actions.CsvChangeEscapeCharacterActionGroup.update(CsvChangeEscapeCharacterActionGroup.java:27)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:158)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$884/0x0000000100c12450.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:181)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:717)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:139)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1461/0x00000001010408c8.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:234)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1860/0x000000010127adc0.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1566/0x00000001010f4dc0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1376/0x0000000100ffbc58.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1377/0x0000000100fea400.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:225)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1859/0x000000010127a1e8.invoke(Unknown Source)
		at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:223)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1857/0x0000000101279d58.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1858/0x0000000101279fa0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:47)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1474/0x0000000101046db0.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
		at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
		at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
		at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
		at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
		at com.intellij.openapi.application.impl.FlushQueue$$Lambda$544/0x00000001005913e8.run(Unknown Source)
		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
		at java.base@17.0.6/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
		at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
		at com.intellij.ide.IdeEventQueue$$Lambda$539/0x000000010058e850.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
		at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
		at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
		at com.intellij.ide.IdeEventQueueKt$$Lambda$537/0x00000001005873a0.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
		at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
		at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
		at com.intellij.ide.IdeEventQueue$$Lambda$533/0x0000000100586cc8.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:254)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$3459/0x0000000101b64d18.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:825)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:252)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:343)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$3454/0x0000000101b64160.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:855)
		at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:342)
		at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.updateChildren(ActionPopupMenuImpl.java:180)
		at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:130)
		at com.intellij.openapi.editor.impl.ContextMenuPopupHandler.handlePopup(ContextMenuPopupHandler.java:36)
		at com.intellij.openapi.editor.impl.EditorImpl.invokePopupIfNeeded(EditorImpl.java:5015)
		at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3971)
		at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3861)
		at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
		at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
		at java.desktop/java.awt.Component.processEvent(Component.java:6421)
		at java.desktop/java.awt.Container.processEvent(Container.java:2266)
		at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
		at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
		at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
		at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
		at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
		at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
		at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
		at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
		at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
		at java.base@17.0.6/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.base@17.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
		at java.base@17.0.6/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
		at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
		at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
		at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
		at com.intellij.ide.IdeEventQueueKt$$Lambda$537/0x00000001005873a0.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
		at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
		at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
		at com.intellij.ide.IdeEventQueue$$Lambda$533/0x0000000100586cc8.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2023.1\plugins\CSVEditor, version=3.1.0-231, package=null, isBundled=false), packagePrefix=null, instanceId=44, state=active)

IDE
---
PyCharm (PC-231.8109.197)

**Comment by SeeSharpSoft** [comment] 2023-05-10 21:35
duplicate of #401

**Closed by SeeSharpSoft** 2023-05-10 21:35 UTC
