### ISSUE TITLE
Formatter: equal column width in text editor (worked, now broken)

### ISSUE THREAD

**Issue by hosswald** [SeeSharpSoft/intellij-csv-validator#385] opened 2022-12-07 11:59 UTC
I don't know exactly why, but recently, the formatter stopped fixing the column width (in text editor). Previously, I could press ctrl+alt+L to format this
```csv
col1,col2,column3
value1,val2,v3
val1,value2,v3
```
into this
```csv
col1  ,col2  ,column3
value1,val2  ,v3
val1  ,value2,v3
```
Now it's not doing it anymore and I can't find any option to enable this again.
I assume it was a feature of this plugin, but it might also have been a native IntelliJ feature that has been removed.

**Comment by violanotes** [comment] 2022-12-20 22:51
I can confirm the same issue with IntelliJ IDEA 2022.2.1 (Community Edition) and CSV Editor 3.0.2-222.

**Comment by SeeSharpSoft** [comment] 2022-12-21 12:38
Duplicate of #374 (thanks for the feedback though, lets consolidate the discussion)

**Closed by SeeSharpSoft** 2022-12-21 12:38 UTC
