### ISSUE TITLE
Past few versions of this plugin don't show colors

### ISSUE THREAD

**Issue by wibotwi** [SeeSharpSoft/intellij-csv-validator#298] opened 2021-06-23 05:29 UTC
CSV files are not colored, all columns are of same color.
Yet it understands columns, cause If I select any word -> it highlights whole column with green.
Table editor - also no colors.

Btw, in settings example file is also not colored, and when I click "Text" it blinks all columns in example, but when I click "Column Color 5" nothing is blinking.

**Comment by wibotwi** [comment] 2021-06-23 05:53
and tooltip is not shown in text editor
so it is hard to tell which column I am editing now

**Comment by SeeSharpSoft** [comment] 2021-06-28 19:31
*Please ensure that the file-type `CSV file` is associated with `*.csv` (Settings -> File Types) and that `Rainbow` is selected for [Value Coloring](https://github.com/SeeSharpSoft/intellij-csv-validator#value-coloring).*

I can't reproduce any of the described behavior, except non-colored settings example. This is caused by the fact that column-vise coloring is applied via an "annotator". This feature seems not to be enabled in the preview window (I am just consuming this preview capability but not controlling its actual behavior).

The tooltips in the editor are also applied via the same annotator... so maybe there is something off with it, like you have a contradicting plugin installed or another annotator implementation is overwriting the one from this plugin. Annotators are usually used to highlight problems or significant places in the editor.

**Comment by SeeSharpSoft** [comment] 2021-07-16 21:33
Similar to #299 - resolved with 2.17.1

**Closed by SeeSharpSoft** 2021-07-16 21:33 UTC
Labels: consulting
