### ISSUE TITLE
[Automated Report] java.lang.IllegalArgumentException: Argument for @NotNull parameter 'replacement' of net/seesharpsoft/intellij/plugins/csv/psi/CsvPsiTreeUpdater$ReplacePsiAction.<init> must not be null

### ISSUE THREAD

**Issue by DanuBizz** [SeeSharpSoft/intellij-csv-validator#382] opened 2022-12-04 23:12 UTC
Message
---
<no message>

Stacktrace
---
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'replacement' of net/seesharpsoft/intellij/plugins/csv/psi/CsvPsiTreeUpdater$ReplacePsiAction.<init> must not be null
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater$ReplacePsiAction.$$$reportNull$$$0(CsvPsiTreeUpdater.java)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater$ReplacePsiAction.<init>(CsvPsiTreeUpdater.java)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater.replaceField(CsvPsiTreeUpdater.java:286)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.setValueAt(CsvTableModelBase.java:180)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.setValue(CsvTableModelBase.java:156)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableModelSwing.setValueAt(CsvTableModelSwing.java:82)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
	at java.desktop/javax.swing.JTable.editingStopped(JTable.java:4785)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.fireStopCellEditing(CsvMultiLineCellRenderer.java:158)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.stopCellEditing(CsvMultiLineCellRenderer.java:144)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.removeCellEditor(JBTable.java:859)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover$1.run(JBTable.java:847)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:174)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:113)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:180)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:133)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:164)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:170)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.permanentFocusOwnerChanged(JBTable.java:824)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.propertyChange(JBTable.java:802)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1501)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:796)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:665)
	at com.intellij.ide.IdeKeyboardFocusManager.lambda$dispatchEvent$0(IdeKeyboardFocusManager.java:48)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:48)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/sun.awt.SunToolkit$1.run(SunToolkit.java:516)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.0.1-222, package=null, isBundled=false), packagePrefix=null, instanceId=92, state=active)

IDE
---
IntelliJ IDEA (IC-222.4345.14)

**Comment by SeeSharpSoft** [comment] 2022-12-05 00:09
Duplicate of #380

**Closed by SeeSharpSoft** 2022-12-05 00:09 UTC
