### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by RABINGG** [SeeSharpSoft/intellij-csv-validator#471] opened 2023-05-30 09:30 UTC
Getting the following exception whenever open a csv scratch file.

**Exception**
> java.lang.Throwable: Assertion failed
> 	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:258)
> 	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:267)
> 	at com.intellij.openapi.editor.impl.ScrollingModelImpl.removeVisibleAreaListener(ScrollingModelImpl.java:387)
> 	at com.intellij.openapi.editor.ScrollingModel.lambda$addVisibleAreaListener$0(ScrollingModel.java:41)
> 	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
> 	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
> 	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
> 	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
> 	at com.intellij.openapi.editor.impl.EditorImpl.lambda$release$11(EditorImpl.java:1048)
> 	at com.intellij.openapi.editor.impl.EditorImpl.executeNonCancelableBlock(EditorImpl.java:1007)
> 	at com.intellij.openapi.editor.impl.EditorImpl.release(EditorImpl.java:1014)
> 	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:250)
> 	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.disposeEditor(TextEditorComponent.kt:129)
> 	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.kt:113)
> 	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.java:149)
> 	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
> 	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
> 	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
> 	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
> 	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:51)
> 	at net.seesharpsoft.intellij.plugins.csv.editor.CsvFileEditorProvider.disposeEditor(CsvFileEditorProvider.java:76)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1660)
> 	at com.intellij.openapi.fileEditor.impl.EditorWindow$closeFile$1.invoke(EditorWindow.kt:564)
> 	at com.intellij.openapi.fileEditor.impl.EditorWindow$closeFile$1.invoke(EditorWindow.kt:546)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$Companion.runBulkTabChange$intellij_platform_ide_impl(FileEditorManagerImpl.kt:390)
> 	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl(EditorWindow.kt:546)
> 	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeFileInWindows(EditorsSplitters.kt:609)
> 	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeFile(EditorsSplitters.kt:590)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$closeFile$3$1$1.invoke(FileEditorManagerImpl.kt:734)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$closeFile$3$1$1.invoke(FileEditorManagerImpl.kt:734)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$Companion.runBulkTabChange$intellij_platform_ide_impl(FileEditorManagerImpl.kt:390)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$lambda$15$lambda$14(FileEditorManagerImpl.kt:734)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.kt:731)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyVirtualFileListener.beforeFileDeletion(FileEditorManagerImpl.kt:1693)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyVirtualFileListener.before(FileEditorManagerImpl.kt:1672)
> 	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
> 	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
> 	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:482)
> 	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:294)
> 	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:442)
> 	at jdk.proxy2/jdk.proxy2.$Proxy175.before(Unknown Source)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$fireBeforeEvents$14(PersistentFSImpl.java:1210)
> 	at com.intellij.util.Suppressions$runSuppressing$1$1.invoke(suppressions.kt:16)
> 	at com.intellij.util.Suppressions$runSuppressing$1$1.invoke(suppressions.kt:16)
> 	at com.intellij.util.Suppressions.runSuppressing(suppressions.kt:23)
> 	at com.intellij.util.Suppressions.runSuppressing(suppressions.kt:16)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.fireBeforeEvents(PersistentFSImpl.java:1209)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$processEvent$5(PersistentFSImpl.java:856)
> 	at com.intellij.util.Suppressions$runSuppressing$1$1.invoke(suppressions.kt:16)
> 	at com.intellij.util.Suppressions$runSuppressing$1$1.invoke(suppressions.kt:16)
> 	at com.intellij.util.Suppressions.runSuppressing(suppressions.kt:23)
> 	at com.intellij.util.Suppressions.runSuppressing(suppressions.kt:16)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:855)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.deleteFile(PersistentFSImpl.java:568)
> 	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.delete(VirtualFileSystemEntry.java:278)
> 	at com.intellij.psi.impl.file.PsiFileImplUtil.doDelete(PsiFileImplUtil.java:68)
> 	at com.intellij.psi.impl.source.PsiFileImpl.delete(PsiFileImpl.java:455)
> 	at com.intellij.refactoring.safeDelete.SafeDeleteProcessor.performRefactoring(SafeDeleteProcessor.java:397)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$10(BaseRefactoringProcessor.java:520)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.callPerformRefactoring(BaseRefactoringProcessor.java:574)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$11(BaseRefactoringProcessor.java:519)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$6(ApplicationImpl.java:938)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
> 	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:150)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$7(ApplicationImpl.java:938)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:946)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runEdtProgressWriteAction(ApplicationImpl.java:936)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithNonCancellableProgressInDispatchThread(ApplicationImpl.java:919)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:518)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$execute$2(BaseRefactoringProcessor.java:333)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:331)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:254)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$19(BaseRefactoringProcessor.java:627)
> 	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:643)
> 	at com.intellij.ide.util.DeleteHandler$1.run(DeleteHandler.java:146)
> 	at com.intellij.refactoring.safeDelete.SafeDeleteDialog.lambda$doOKAction$0(SafeDeleteDialog.java:180)
> 	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:170)
> 	at com.intellij.refactoring.safeDelete.SafeDeleteDialog.doOKAction(SafeDeleteDialog.java:178)
> 	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1863)
> 	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1817)
> 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
> 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
> 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
> 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
> 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
> 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
> 	at com.intellij.openapi.ui.DialogWrapper$4.actionPerformed(DialogWrapper.java:1363)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
> 	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
> 	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:599)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
> 	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
> 	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
> 	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
> 	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:741)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:466)
> 	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1675)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1633)
> 	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1647)
> 	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:156)
> 	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:122)
> 	at com.intellij.ide.projectView.impl.ProjectViewDeleteElementProvider.deleteElement(ProjectViewDeleteElementProvider.java:58)
> 	at com.intellij.ide.actions.DeleteAction.actionPerformed(DeleteAction.java:33)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
> 	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
> 	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:599)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
> 	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
>

**Comment by SeeSharpSoft** [comment] 2023-05-30 13:18
Duplicate of #373

**Closed by SeeSharpSoft** 2023-05-30 13:18 UTC
