### ISSUE TITLE
[Automated Report] java.lang.IllegalArgumentException: Argument for @NotNull parameter 'replacement' of net/seesharpsoft/intellij/plugins/csv/psi/CsvPsiTreeUpdater$ReplacePsiAction.<init> must not be null

### ISSUE THREAD

**Issue by DanuBizz** [SeeSharpSoft/intellij-csv-validator#381] opened 2022-12-04 23:12 UTC
Message
---
<no message>

Stacktrace
---
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'replacement' of net/seesharpsoft/intellij/plugins/csv/psi/CsvPsiTreeUpdater$ReplacePsiAction.<init> must not be null
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater$ReplacePsiAction.$$$reportNull$$$0(CsvPsiTreeUpdater.java)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater$ReplacePsiAction.<init>(CsvPsiTreeUpdater.java)
	at net.seesharpsoft.intellij.plugins.csv.psi.CsvPsiTreeUpdater.replaceField(CsvPsiTreeUpdater.java:286)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.setValueAt(CsvTableModelBase.java:180)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.CsvTableModelBase.setValue(CsvTableModelBase.java:156)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvTableModelSwing.setValueAt(CsvTableModelSwing.java:82)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
	at java.desktop/javax.swing.JTable.editingStopped(JTable.java:4785)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.fireStopCellEditing(CsvMultiLineCellRenderer.java:158)
	at net.seesharpsoft.intellij.plugins.csv.editor.table.swing.CsvMultiLineCellRenderer.stopCellEditing(CsvMultiLineCellRenderer.java:144)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.removeCellEditor(JBTable.java:859)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover$1.run(JBTable.java:847)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:174)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:113)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:180)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:133)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:164)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:170)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.permanentFocusOwnerChanged(JBTable.java:824)
	at com.intellij.ui.table.JBTable$MyCellEditorRemover.propertyChange(JBTable.java:802)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1501)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:796)
	at java.desktop/java.awt.Component.removeNotify(Component.java:7143)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2851)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/javax.swing.JTable.removeNotify(JTable.java:879)
	at com.intellij.ui.table.JBTable.removeNotify(JBTable.java:511)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeNotify(JBTabsImpl.java:843)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.remove(Container.java:1235)
	at com.intellij.ui.tabs.impl.JBTabsImpl.remove(JBTabsImpl.java:828)
	at java.desktop/java.awt.Container.remove(Container.java:1293)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeDeferredNow(JBTabsImpl.java:1666)
	at com.intellij.ui.tabs.impl.JBTabsImpl.lambda$removeDeferred$16(JBTabsImpl.java:1639)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:113)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:180)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:133)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:164)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeDeferred(JBTabsImpl.java:1645)
	at com.intellij.ui.tabs.impl.JBTabsImpl.lambda$executeSelectionChange$13(JBTabsImpl.java:1551)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.openapi.util.ActionCallback.doWhenProcessed(ActionCallback.java:129)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:1546)
	at com.intellij.ui.tabs.impl.JBTabsImpl$14.run(JBTabsImpl.java:1487)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$1(EditorTabbedContainer.java:123)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$2(EditorTabbedContainer.java:121)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:1483)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:1472)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$EditorTabs.select(EditorTabbedContainer.java:782)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:89)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6645)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Plugin
---
PluginClassLoader(plugin=PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\CSVEditor, version=3.0.1-222, package=null, isBundled=false), packagePrefix=null, instanceId=92, state=active)

IDE
---
IntelliJ IDEA (IC-222.4345.14)

**Comment by SeeSharpSoft** [comment] 2022-12-05 00:09
Duplicate of #380

**Closed by SeeSharpSoft** 2022-12-05 00:09 UTC
