### ISSUE TITLE
[Suggestion]Search in table view

### ISSUE THREAD

**Issue by kdschlosser** [SeeSharpSoft/intellij-csv-validator#218] opened 2020-05-13 18:39 UTC
I believe this may have been mentioned. If it has then this can get closed. Adding a full regex enabled search feature to the table view. This search feature should search a column row or cell if selected or if none of the above is selected then to search the whole table.

**Comment by SeeSharpSoft** [comment] 2020-05-15 17:08
Duplicate of #93

**Closed by SeeSharpSoft** 2020-05-15 17:08 UTC
