### ISSUE TITLE
Column highlighting still occurring when disabled

### ISSUE THREAD

**Issue by MarkJeronimus** [SeeSharpSoft/intellij-csv-validator#231] opened 2020-06-25 14:29 UTC
When column highlighting is disabled, columns are no longer highlighted when the caret moves to another column because of user interaction (arrow keys, mouse click).

But column highlighting still occurs when the caret moves because of Find actions (Ctrl+F, F3, ...)

**Comment by SeeSharpSoft** [comment] 2020-07-14 07:47
Hi @MarkJeronimus - not sure whether I get you right, but [disabling column highlighting](https://github.com/SeeSharpSoft/intellij-csv-validator#enable-column-highlighting) does only disable the [Column Hightlighting features](https://github.com/SeeSharpSoft/intellij-csv-validator#column-highlighting-colors). It doesn't affect the feature of highlighting the column of a currently selected value, if this is what you try to do. If so, is this really an option you would like to have?

**Comment by MarkJeronimus** [comment] 2020-07-14 09:03
In my book, 'to highlight' means to emphasize something to draw your attention. If "column highlighting" is a feature to give every column a color, then I don't think it should be called 'highlighting'.

The issue I'm having is that with the 'column highlighting' checkbox enabled, placing the cursor in a certain column will highlight that single column. Placing the cursor on an empty line removes any highlighted column. Whatever this behavior is, it stops when I uncheck that checkbox. I want the same to happen also when I search for a word, and the editor selects a match.

**Comment by SeeSharpSoft** [comment] 2020-07-14 21:07
Thats a good point, I have to agree: should be named "Column Coloring" instead of "Column Highlighting".

However, this setting does not influence the actual "real" column highlighting. I double checked the [implementation](https://github.com/SeeSharpSoft/intellij-csv-validator/blob/master/src/main/java/net/seesharpsoft/intellij/plugins/csv/highlighter/CsvHighlightUsagesHandler.java) and it has no dependency to any setting (by design).

Furthermore, the column highlighting is only applied if at least one character is selected. And when searching, only the search results are highlighted. To highlight the corresponding column, the search result must be selected in the editor. This is actually wanted behavior, avoiding to mix column highlighting with search result hightlighting.

Do you have any other plugins installed that might alter the described behavior? Which IDE/version are you using?

**Comment by SeeSharpSoft** [comment] 2020-08-13 16:12
@MarkJeronimus The option itself is no more due to a big refactoring, where I also renamed "Column Highlight Color" to "Column Color" resp. "Value Coloring".

The actual column highlighting (when marking text) is still intact and still independent of those settings. Therefore I am closing this issue.

**Closed by SeeSharpSoft** 2020-08-13 16:12 UTC
Labels: consulting
